name: Deploy AWS Instance with Terraform

on:
  push:
    branches:
      - main  # Запуск при пуше в ветку main

jobs:
  terraform:
    runs-on: ubuntu-latest  # Используем Ubuntu для работы

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Шаг для получения кода репозитория

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2  # Шаг для установки Terraform
      - name: Debug AWS credentials
        run: echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
      - name: Debug AWS credentials
        run: echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      - name: Terraform Init
        run: terraform init  # Инициализация Terraform

      - name: Terraform Plan
        run: terraform plan  # Передаем AMI ID из секретов

      - name: Terraform Apply
        run: terraform apply  # Применяем изменения
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Учетные данные для доступа
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}