name: Deploy AWS Instance with Terraform

on:
  push:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
    
    - name: Terraform Init
      run: terraform init
    
    - name: Terraform Plan
      run: terraform plan -var "ami_id=ami-0d17018cef51af497"
    
    - name: Terraform Apply
      run: terraform apply -auto-approve -var "ami_id=ami-0d17018cef51af497"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
